### ISSUE TITLE
Deploy Containerized Services

### ISSUE THREAD

**Issue by ClementBobin** [Latitude-OpenDATA-SIO-Saintbe/setup#17]
I installed tailscale on both machines to deploy the VMs on portainer and ensure that developers also have access to the machines. It is possible with this tool to connect to the machines via remote desktop, while deploying the machines and their contents which are containerized. : 

![Image](https://github.com/user-attachments/assets/82c12acb-a786-46da-972c-67da8c013e27)

The "tailscale up" command is used to get the link to transmit the VM to portainer : 

![Image](https://github.com/user-attachments/assets/4ab4f8ff-2051-418c-b2f7-cb3ff12a5168)

I installed Tailscale on my physical Windows machine to connect it too : 
![Image](https://github.com/user-attachments/assets/76b07a62-f67a-4958-92b4-a6b66189ba50)

Install portnaire on the VM debian glpi : 
![Image](https://github.com/user-attachments/assets/faec31a2-a838-4392-8dce-7f9ed580fa0a)

**Comment by ValerieLecourbe** [comment]
Updated the script which allows you to download and launch everything at once (clone-repos.sh)

![Image](https://github.com/user-attachments/assets/c7667c68-2daf-418d-abe3-a38dce7be303)


![Image](https://github.com/user-attachments/assets/d8e4795b-e5ac-49ec-8f79-ba2b23119cc8)


![Image](https://github.com/user-attachments/assets/4218e220-c943-4921-a77b-627d6c522d51)

**Comment by ValerieLecourbe** [comment]
Creating tailscale keys

![Image](https://github.com/user-attachments/assets/dc33be36-c0fc-460c-ae98-5d11f91de0ed)

**Comment by ValerieLecourbe** [comment]
Acceptance criteria:
Optimized images:
Container images are based on lightweight bases, unless specifically needed.
Images are correctly versioned (v1.0, v1.1, latest only in development).
Tests:
Images have been tested locally and work without errors.
