### ISSUE TITLE
Create Infrastructure Schema

### ISSUE THREAD

**Issue by ClementBobin** [Latitude-OpenDATA-SIO-Saintbe/setup#25]
In this task, the infrastructure design for the project will be created. This involves specifying the physical or cloud-based infrastructure that will support the application, including network design, security protocols, resource allocation (e.g., servers, storage), and deployment pipelines. The schema must account for scalability, resilience, and security, ensuring that the infrastructure is robust and capable of supporting the application in production environments.

**Comment by ValerieLecourbe** [comment]
![Image](https://github.com/user-attachments/assets/8cebf315-574c-49d8-8484-a44cef24ee48)

**Comment by ValerieLecourbe** [comment]
Acceptance criteria: The network must allow all the flows necessary for the activity (e.g. access to applications, services, storage, etc.).
Must correspond to current needs
Write the utility of each machine

**Comment by ValerieLecourbe** [comment]
![Image](https://github.com/user-attachments/assets/2189771a-1f0c-4dcc-946f-c0722d23e04c)
