### ISSUE TITLE
Creating a Virtual Machine to Host GLPI

### ISSUE THREAD

**Issue by ClementBobin** [Latitude-OpenDATA-SIO-Saintbe/setup#26]
As a System Administrator,
I want to create and configure a virtual machine (VM) to host GLPI (Gestionnaire Libre de Parc Informatique),
so that I can manage IT assets and service requests efficiently within the organization.

I installed a local Linux Debian 11 virtual machine which contains GLPI, I downloaded it and it works now.

![Image](https://github.com/user-attachments/assets/597cef27-a5ea-49f2-b962-d4cd21e06950)

**Comment by ValerieLecourbe** [comment]
Acceptance Criteria:
The number of cores and frequency meet the requested specifications.
The amount of RAM allocated meets the application needs and expected loads.
Storage:
The virtual disk size is sufficient for the operating system, applications, and data.
Operating System:
The operating system (and its version) is correctly installed.

**Comment by ValerieLecourbe** [comment]
Script to install glpi :

git clone https://github.com/Latitude-OpenDATA-SIO-Saintbe/AutomatisationScript.git
cd AutomatisationScript
```

Make the scripts executable:

```bash
chmod +x bash/*/script.sh
chmod +x bash/script.sh
```

Run the main installation script:

```bash

    bash bash/script.sh
```

    Follow the prompt: The script will ask you to choose the service you want to install:
        Apache
        Docker (with Portainer)
        Firewall
        GLPI

    Type the number corresponding to your choice, and the script will automatically install and configure the selected service.
