### ISSUE TITLE
Creating a Virtual Machine to Host Docker

### ISSUE THREAD

**Issue by ClementBobin** [Latitude-OpenDATA-SIO-Saintbe/setup#27]
As a System Administrator,
I want to create and configure a virtual machine (VM) to host Docker,
so that I can deploy containerized applications and services efficiently in a controlled environment.

I installed a virtual machine that allows hosting docker containers.

I installed the git tool with command "apt install git" and curl

Git clone command to clone script from repos

![Image](https://github.com/user-attachments/assets/c6a77341-6057-4302-8b51-31297e2ee49d)

Right of access to the file in which I am located :

![Image](https://github.com/user-attachments/assets/b23ae2a0-3afc-4531-a679-6833e22a63dd)

git clone https://github.com/Latitude-OpenDATA-SIO-Saintbe/AutomatisationScript.git
cd AutomatisationScript
```

Make the scripts executable:

```bash
chmod +x bash/*/script.sh
chmod +x bash/script.sh
```

Run the main installation script:

```bash

    bash bash/script.sh
```

    Follow the prompt: The script will ask you to choose the service you want to install:
       1) Apache
        2) Docker (with Portainer)
        3) Firewall
        4) GLPI

I did the 2

**Comment by ValerieLecourbe** [comment]
Acceptance Criteria:
The number of cores and frequency meet the requested specifications.
The amount of RAM allocated meets the application needs and expected loads.
Storage:
The virtual disk size is sufficient for the operating system, applications, and data.
Operating System:
The operating system (and its version) is correctly installed.
